export const clientMockData =
//   {
//   first_name: "King",
//   last_name: "Tiger",
//   full_name: "King Tiger Client",
//   password: "19981011",
//   business_name: "Doe Enterprises",
//   personal_address: "123 Main St, Springfield",
//   business_address: "456 Business Rd, Springfield",
//   position: "CEO",
//   email: "kingtiger@client.com",
//   phone: "123-456-7890",
//   preferred_contact_method: "email",
//   timezone: "GMT-5",
//   default_services: "Consulting, Development",
//   other_services: "Marketing",
//   priorities: "Quality, Speed",
//   support_hours: "9 AM - 5 PM",
//   use_tools: "Slack, Trello",
//   access_specific: true,
//   file_share_method: "Google Drive",
//   required_access: "CRM, Project Management",
//   often: "Weekly",
//   receive_updates: "Yes",
//   key_people: "Jane Doe, CFO",
//   particular_task: "Website Redesign",
//   start_date: "2024-03-01",
//   billing_method: "Hourly",
//   billing_cycle: "Monthly",
//   invoice_email: "billing@doeenterprises.com",
//   emergency_contact_name: "Jane Doe",
//   emergency_contact_phone: "987-654-3210",
//   emergency_relationship: "Spouse",
//   digital_sign: "JohnDoeSignature.png",
//   sign_date: "2024-02-28",
// }
  
  {
  "first_name": "Jason",
  "last_name": "Steven",
  "email": "kingtiger0001@client.com",
  "sex": "man",
  "password": "19981011",
  "address": "asdf",
  "phone": 1231231231,
  "city": "asdf",
  "state": "asdf",
  "country": "asdf",
  "zip": "asdf",
  "dob": "2024-11-13",
  "doj": "2024-11-24",
  "status": 1,
  "preferred_correspondence_email": "asdf",
  "preferred_contact_method": "asdf",
  "business_address": "asdf",
  "address_line_1": "asdf",
  "address_line_2": "asdf",
  "state_province_region": "asdf",
  "company": "asdf",
  "postal_zip_code": "asdf",
  "prefer_company": true,
  "signature": "asdf",
  "agree_terms": true,
  "often": "weekly",
  "agree_update_terms": true}