'use client';
import TimeTrackRecord1 from '@/components/timer/TimeTrackRecord1';
import { fetchTodayTimeTracksForAllUsers } from '@/hooks/api-hooks';
import type { TypeTimeTrack } from '@/lib/types';
import { calculateTotalDuration } from '@/lib/utils/date';
import { isNonEmptyArray } from '@/lib/utils/functions';
import { useEffect, useState } from 'react';
import WeekNavigation from "@/components/timer/WeekNavigation";
import TimerModal from '@/components/modal/timerModal';
import CurrentTracks from "@/components/timer/CurrentTracks";
import StopWatch from "@/components/timer/StopWatch";

const Timer = () => {
  const [timeTracks, setTimeTracks] = useState<TypeTimeTrack[]>([
    {
      id: 1,
      start_time: new Date('2025-02-25T08:00:00'),
      end_time: new Date('2025-02-25T09:00:00'),
      estimated_time: 60,
      title: 'Designing Project Logo',
      projectId: 101,
      userId: 1001,
      clientId: 201,
      taskId: 301,
      timeTrackProject: {
        id: 101,
        title: 'Website Development',
        clientId: 201,
        monthly_hours: 40,
        rate: 50,
        start_date: '2025-02-01',
        rollover: false,
        platforms: 'Web',
        duration: '6 months',
        state: 'In Progress',
        services: 'Design and Development',
        project_type: 'Development',
        technology: 'React, Node.js',
        additional_setting: 'None',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 201,
        full_name: 'John Doe',
        email: 'john.doe@example.com',
        phone: '123-456-7890',
        business_name: 'Doe Enterprises',
        personal_address: '1234 Elm St.',
        business_address: '5678 Oak St.',
        position: 'CEO',
        preferred_contact_method: 'Email',
        timezone: 'UTC',
        default_services: 'Web Design, Development',
        other_services: 'SEO, Marketing',
        priorities: 'High',
        support_hours: '9am-6pm',
        use_tools: 'Trello, Slack',
        access_specific: true,
        file_share_method: 'Email',
        required_access: 'Full Access',
        often: 'Daily',
        receive_updates: 'Yes',
        key_people: 'John Doe',
        particular_task: 'Website Redesign',
        start_date: '2025-01-01',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@doeenterprises.com',
        emergency_contact_name: 'Jane Doe',
        emergency_contact_phone: '123-456-7891',
        emergency_relationship: 'Spouse',
        digital_sign: 'signed',
        sign_date: '2025-02-20',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1001,
        first_name: 'Alice',
        last_name: 'Johnson',
        full_name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        phone: '555-123-4567',
        position: 'Designer',
        role: 'Lead Designer',
        avatar: 'http://example.com/avatar1.jpg',
        dob: '1990-05-12',
        address: '123 Designer St.',
        city: 'Design City',
        state: 'CA',
        country: 'USA',
        zip_code: '90001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar1.jpg'
      },
      timeTrackTask: {
        id: 301,
        title: 'Logo Design',
        projectId: 101,
        due_date: '2025-02-28',
        priority: 'High',
        description: 'Design a new logo for the website.',
        estimated_time: 4,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 2,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 3,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 4,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
    {
      id: 5,
      start_time: new Date('2025-02-25T09:00:00'),
      end_time: new Date('2025-02-25T10:30:00'),
      estimated_time: 90,
      title: 'Develop Homepage',
      projectId: 102,
      userId: 1002,
      clientId: 202,
      taskId: 302,
      timeTrackProject: {
        id: 102,
        title: 'E-Commerce Website',
        clientId: 202,
        monthly_hours: 60,
        rate: 60,
        start_date: '2025-02-01',
        rollover: true,
        platforms: 'Web, Mobile',
        duration: '4 months',
        package_level: 'Premium',
        state: 'In Progress',
        services: 'Web Development',
        project_type: 'Development',
        technology: 'React, Express',
        additional_setting: 'Responsive',
        portal_access: 'Client Portal',
        assignedProjectUser: [],
        requestedProjectClient: [],
        projectTask: [],
        projectTimeTrack: []
      },
      timeTrackClient: {
        id: 202,
        full_name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        business_name: 'Smith Inc.',
        personal_address: '789 Maple St.',
        business_address: '123 Pine Ave.',
        position: 'CTO',
        preferred_contact_method: 'Phone',
        timezone: 'UTC+1',
        default_services: 'E-commerce solutions',
        other_services: 'SEO, Marketing',
        priorities: 'Medium',
        support_hours: '9am-5pm',
        use_tools: 'Jira, Slack',
        access_specific: true,
        file_share_method: 'Dropbox',
        required_access: 'Read-Only',
        often: 'Weekly',
        receive_updates: 'Yes',
        key_people: 'Jane Smith',
        particular_task: 'Homepage Development',
        start_date: '2025-01-10',
        billing_method: 'Hourly',
        billing_cycle: 'Monthly',
        invoice_email: 'billing@smithinc.com',
        emergency_contact_name: 'Mark Smith',
        emergency_contact_phone: '987-654-3201',
        emergency_relationship: 'Husband',
        digital_sign: 'signed',
        sign_date: '2025-02-15',
        requestedClientProject: [],
        clientTask: [],
        clientTimeTrack: []
      },
      timeTrackUser: {
        id: 1002,
        first_name: 'Bob',
        last_name: 'Williams',
        full_name: 'Bob Williams',
        email: 'bob.williams@example.com',
        phone: '555-987-6543',
        position: 'Developer',
        role: 'Frontend Developer',
        avatar: 'http://example.com/avatar2.jpg',
        dob: '1985-09-10',
        address: '456 Developer St.',
        city: 'Tech City',
        state: 'TX',
        country: 'USA',
        zip_code: '75001',
        status: 'Active',
        assignedUserProject: [],
        assignedUserTask: [],
        userTimeTrack: [],
        image: 'http://example.com/avatar2.jpg'
      },
      timeTrackTask: {
        id: 302,
        title: 'Build Homepage Layout',
        projectId: 102,
        due_date: '2025-02-26',
        priority: 'High',
        description: 'Create the layout for the homepage of the e-commerce website.',
        estimated_time: 5,
        state: 'In Progress',
        taskProject: [],
        taskClient: [],
        assignedTaskUser: [],
        taskTimeTrack: []
      }
    },
]);

  const [totalDaily, setTotalDaily] = useState<string>('');
  const [period, setPeriod] = useState<string>('daily');

  useEffect(() => {
    const getTimeTracks = async () => {
      const timeTracks = await fetchTodayTimeTracksForAllUsers();
      setTimeTracks(timeTracks);
      const totalDaily = calculateTotalDuration(timeTracks);
      setTotalDaily(totalDaily);
    };

    getTimeTracks();
  }, []);

  if (!timeTracks) {
    return (
      <div className="w-full h-full bg-yellow-50 border rounded-xl justify-items-center py-8">
        <h3 className="text-red-300 text-lg pb-3 font-bold">
          No time tracks for today
        </h3>
        <p className="text-blue-400 italic">
          Looks like you haven&#39;t started tracking your activities yet. Ready
          to begin?
        </p>
      </div>
    );
  }
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  
  const openModal = () => {
    setIsModalOpen(true);
  };
  
  const closeModal = () => {
    setIsModalOpen(false);
  };
  return (
    <div className="pt-20 pl-64 pr-6  min-h-screen w-screen overflow-x-hidden bg-yellow-50 border rounded-xl justify-items-center">
      <div className="flex flex-row w-full px-4 py-4">
        <div className="flex flex-row space-between w-full gap-5">
          <p>Select the period that you want to see:</p>
          <select
            id="project"
            name="project"
            value={period}
            required
            className="border rounded-md selection:default:"
            onChange={(e) => {
              setPeriod(e.target.value);
            }}
          >
            <option value={'Daily'} className="bg-green-400">
              Daily
            </option>
            <option value={'Weekly'} className="bg-red-300">
              Weekly
            </option>
            <option value={'Monthly'} className="bg-yellow-400">
              Monthly
            </option>
            <option value={'6 Months'} className="bg-blue-300">
              6 Months
            </option>
          </select>
        </div>
        <div className="mr-5">
           <WeekNavigation />
        </div>
      </div>
      <div className="w-full">
        <h3 className="w-full border rounded-t-xl text-center bg-gradient-to-l from-[#27F090] via-[#7F41F3] to-[#F59527] px-4 py-4 md:px-10 text-[35px] font-bold text-white">
          Logged Total time for {period}: {totalDaily}
        </h3>
        <ul className="py-4 flex flex-row w-full flex-wrap">
          {isNonEmptyArray(timeTracks) &&
            timeTracks.map((track: TypeTimeTrack, index: number) => (
              <div key={index} className="w-1/2 px-3">
                <TimeTrackRecord1 {...track} />
              </div>
            ))}
        </ul>
      </div>
      <button
        className="absolute right-24 bottom-24 p-2 bg-blue-500 text-white"
        onClick={openModal}
      >
        Start Task Timer
      </button>
      
      <TimerModal isOpen={isModalOpen} closeModal={closeModal} />
    </div>
  );
};

export default Timer;

